Repository googleapis/python-tpu, pull requests merged in 2021-08, with the labels that each got.

#28 feat: bump release level to production/stable
  .repo-metadata.json
  README.rst
  docs/README.rst
  setup.py
Labels: api: tpu, automerge, cla: yes

#32 chore: generate python samples templates in owlbot.py
  owlbot.py
Labels: automerge, cla: yes, samples, api: tpu

#36 chore: migrate to main branch
  .kokoro/build.sh
  .kokoro/test-samples-impl.sh
  CONTRIBUTING.rst
  owlbot.py
Labels: cla: yes, api: tpu
